ALTER TABLE "BAGS" ADD COLUMN IF NOT EXISTS "TITLE" VARCHAR(100);

UPDATE "BAGS" SET "TITLE"='Title 1' WHERE ID = 1;
UPDATE "BAGS" SET "TITLE"='Title 2' WHERE ID = 2;
UPDATE "BAGS" SET "TITLE"='Title 3' WHERE ID = 3;

ALTER TABLE "BAGS" ALTER COLUMN "TITLE" SET NOT NULL;